module.exports = Object.freeze({
  BOTNAME: 'File Fetcher Bot',
  OWNER: '@Krxuvv',
  MENU_THUMB: 'https://telegra.ph/file/fa85a52faaac1973d9e53.jpg',
  
  MESSAGE_ERROR_TRY_AGAIN: 'Error, try again later',
  MESSAGE_INVALID_URL: 'Invalid URL',

  COMMAND_COMMANDS: '/commands',
  COMMAND_UUID: '/uuid',
  COMMAND_SHORT: '/short',
  COMMAND_SLUG: '/slug',
  COMMAND_HEX: '/hex',
  COMMAND_MD5: '/md5',
  COMMAND_BCRYPT: '/bcrypt',
  COMMAND_BINARY: '/binary',
  COMMAND_AI: '/ai ',
  COMMAND_GOOGLE: '/google ',
  COMMAND_BRAINLY: '/brainly ',
  COMMAND_PINTEREST_S: '/pin ',
  
  COMMAND_AI_REGEX: /\/ai (.+)/,
  COMMAND_GOOGLE_REGEX: /\/google (.+)/,
  COMMAND_BRAINLY_REGEX: /\/brainly (.+)/,
  COMMAND_FACEBOOK_REGEX: /^https?:\/\/(www\.)?(m\.)?facebook\.com\/.+/,
  COMMAND_GITHUB_REGEX: /(?:https|git)(?::\/\/|@)github\.com[\/:]([^\/:]+)\/(.+)/i,
  COMMAND_INSTAGRAM_REGEX: /(https?:\/\/)?(www\.)?(instagram\.com)\/.+/,
  COMMAND_SPOTIFY_TRACK_REGEX: /(https?:\/\/)?(www\.)?(open\.spotify\.com|spotify\.?com)\/track\/.+/,
  COMMAND_SPOTIFY_PLAYLIST_REGEX: /(https?:\/\/)?(www\.)?(open\.spotify\.com|spotify\.?com)\/playlist\/.+/,
  COMMAND_SPOTIFY_ALBUM_REGEX: /(https?:\/\/)?(www\.)?(open\.spotify\.com|spotify\.?com)\/album\/.+/,
  COMMAND_THREADS_REGEX: /^https?:\/\/(www\.)?threads\.net\/.+/,
  COMMAND_TIKTOK_REGEX: /https?:\/\/(?:.*\.)?tiktok\.com/,
  COMMAND_X_REGEX: /https?:\/\/(?:.*\.)?twitter\.com/,
  COMMAND_YOUTUBE_REGEX: /^(?:https?:\/\/)?(?:www\.|m\.|music\.)?youtu\.?be(?:\.com)?\/?.*(?:watch|embed)?(?:.*v=|v\/|\/)([\w\-_]+)\&?/,
  COMMAND_PINTEREST_REGEX: /(https?:\/\/)?(www\.)?(pinterest\.ca|pinterest\.?com|pin\.?it)\/.+/,
  COMMAND_PINTEREST_S_REGEX: /\/pin (.+)/,
  
  COMMAND_SHORT_REGEX: /\/short (.+)/,
  COMMAND_SLUG_REGEX: /\/slug (.+)/,
  COMMAND_HEX_REGEX: /\/hex (.+)/,
  COMMAND_MD5_REGEX: /\/md5 (.+)/,
  COMMAND_BCRYPT_REGEX: /\/bcrypt (.+)/,
  COMMAND_UUID_REGEX: /\/uuid/,
  COMMAND_BINARY_REGEX: /\/binary (.+)/,

  ON_MESSAGE: 'message',
});
